//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int idCliente { get; set; }
        public int idTipoCliente { get; set; }
        public Nullable<int> percepcionIIBB { get; set; }
        public int idTipoConvenioIIBB { get; set; }
        public Nullable<int> percepcionComEInd { get; set; }
        public int idTipoConvenioComEInd { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string razonSocial { get; set; }
        public int cuit { get; set; }
        public int ingBrutos { get; set; }
        public string domicilio { get; set; }
        public string email { get; set; }
        public string localidad { get; set; }
        public string telefono { get; set; }
        public int habilitado { get; set; }
        public int pagoCtaCte { get; set; }
    
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual TipoConvenioIIBB TipoConvenioIIBB { get; set; }
        public virtual TipoConvenioComEInd TipoConvenioComEInd { get; set; }
    }
}
