//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoConvenioComEInd
    {
        public TipoConvenioComEInd()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int idTipoConvenioComEInd { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
